services:
  db:
    image: postgres:15
    container_name: coursesphere_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: coursesphere
    ports:
      - "5433:5432" # Mudamos a porta da sua máquina para 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: